const POPULATION_HOUSING_CENSUS_THEME_VARIANT_KEY = 'POPULATION_HOUSING_CENSUS_THEME_VARIANT_KEY';
const POPULATION_HOUSING_CENSUS_LANGUAGE = 'POPULATION_HOUSING_CENSUS_LANGUAGE';
const BASE_URL = 'http://52.54.87.29';
// const BASE_URL = 'http://localhost:8000/';

export const POPULATION_HOUSING_CENSUS_CONSTANTS = {
    BASE_URL,
    POPULATION_HOUSING_CENSUS_THEME_VARIANT_KEY,
    POPULATION_HOUSING_CENSUS_LANGUAGE
};